import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireAuth, requireWorkspace } from "@/lib/api-helpers";

export async function GET(req: NextRequest) {
  const { userId, error } = await requireAuth();
  if (error) return error;
  const { workspace, error: wsError } = await requireWorkspace(userId);
  if (wsError) return wsError;

  const url = new URL(req.url);
  const type = url.searchParams.get("type") ?? "pipeline";
  const clientId = url.searchParams.get("clientId");
  const wid = workspace.id;

  if (type === "client" && clientId) {
    return generateClientReport(clientId, wid, workspace.name, workspace.brandColor);
  }
  return generatePipelineReport(wid, workspace.name, workspace.brandColor);
}

async function generateClientReport(clientId: string, workspaceId: string, wsName: string, brandColor: string) {
  const client = await prisma.client.findFirst({
    where: { id: clientId, workspaceId },
    include: {
      currentStage: { select: { name: true, color: true } },
      pipeline: { select: { name: true } },
      assignedTo: { select: { name: true } },
      activities: { orderBy: { createdAt: "desc" }, take: 20, include: { user: { select: { name: true } } } },
      documents: { select: { name: true, createdAt: true } },
    },
  });
  if (!client) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const daysInStage = Math.floor((Date.now() - new Date(client.stageEnteredAt).getTime()) / 86_400_000);

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${client.name} - Client Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 700px; margin: 0 auto; padding: 40px 20px; color: #1a1a1a; }
  h1 { font-size: 24px; margin-bottom: 4px; }
  h2 { font-size: 16px; margin-top: 32px; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; color: #374151; }
  .header { border-left: 4px solid ${brandColor}; padding-left: 16px; margin-bottom: 24px; }
  .meta { color: #6b7280; font-size: 13px; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 12px; font-weight: 600; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 8px; }
  td { padding: 6px 0; border-bottom: 1px solid #f3f4f6; }
  td:first-child { color: #6b7280; width: 140px; }
  .activity { padding: 8px 0; border-bottom: 1px solid #f3f4f6; font-size: 13px; }
  .activity-time { color: #9ca3af; font-size: 11px; }
  .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 11px; }
  @media print { body { padding: 0; } }
</style></head><body>
<div class="header">
  <p class="meta">${wsName}</p>
  <h1>${client.name}</h1>
  <p class="meta">${client.pipeline?.name ?? ""} · ${client.currentStage?.name ?? "No stage"} · ${daysInStage}d in stage</p>
</div>
<h2>Details</h2>
<table>
  <tr><td>Email</td><td>${client.email ?? "—"}</td></tr>
  <tr><td>Phone</td><td>${client.phone ?? "—"}</td></tr>
  <tr><td>Company</td><td>${client.companyName ?? "—"}</td></tr>
  <tr><td>Project Type</td><td>${client.projectType ?? "—"}</td></tr>
  <tr><td>Project Value</td><td>${client.projectValue ? `$${client.projectValue.toLocaleString()}` : "—"}</td></tr>
  <tr><td>Status</td><td>${client.status}</td></tr>
  <tr><td>Assigned To</td><td>${client.assignedTo?.name ?? "—"}</td></tr>
  <tr><td>Added</td><td>${new Date(client.createdAt).toLocaleDateString()}</td></tr>
</table>
${client.notes ? `<h2>Notes</h2><p style="font-size:13px;white-space:pre-wrap">${client.notes}</p>` : ""}
<h2>Activity (${client.activities.length})</h2>
${client.activities.map((a) => `<div class="activity"><strong>${a.title}</strong>${a.user?.name ? ` · ${a.user.name}` : ""}<br><span class="activity-time">${new Date(a.createdAt).toLocaleString()}</span></div>`).join("")}
${client.documents.length > 0 ? `<h2>Documents (${client.documents.length})</h2>${client.documents.map((d) => `<div class="activity">${d.name}<br><span class="activity-time">${new Date(d.createdAt).toLocaleDateString()}</span></div>`).join("")}` : ""}
<div class="footer">Generated by Cadence · ${new Date().toLocaleDateString()}</div>
<script>window.print()</script>
</body></html>`;

  return new NextResponse(html, { headers: { "Content-Type": "text/html" } });
}

async function generatePipelineReport(workspaceId: string, wsName: string, brandColor: string) {
  const [pipelines, clients] = await Promise.all([
    prisma.pipeline.findMany({
      where: { workspaceId, isActive: true },
      include: { stages: { orderBy: { order: "asc" } } },
    }),
    prisma.client.findMany({
      where: { workspaceId },
      select: { id: true, name: true, status: true, projectValue: true, currentStageId: true, stageEnteredAt: true },
    }),
  ]);

  const now = Date.now();
  const active = clients.filter((c) => c.status === "ACTIVE");
  const completed = clients.filter((c) => c.status === "COMPLETED").length;
  const lost = clients.filter((c) => c.status === "LOST").length;
  const totalValue = active.reduce((s, c) => s + (c.projectValue ?? 0), 0);

  const pipelineRows = pipelines.map((p) => {
    const stageRows = p.stages.map((s) => {
      const inStage = active.filter((c) => c.currentStageId === s.id);
      const overdue = s.daysExpected ? inStage.filter((c) => (now - new Date(c.stageEnteredAt).getTime()) / 86_400_000 > s.daysExpected!).length : 0;
      return `<tr><td style="padding-left:24px">${s.name}</td><td>${inStage.length}</td><td>${overdue > 0 ? `<span style="color:#dc2626">${overdue}</span>` : "—"}</td><td>$${inStage.reduce((s, c) => s + (c.projectValue ?? 0), 0).toLocaleString()}</td></tr>`;
    }).join("");
    return `<tr style="background:#f9fafb;font-weight:600"><td>${p.name}</td><td colspan="3">${p.stages.length} stages</td></tr>${stageRows}`;
  }).join("");

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Pipeline Report - ${wsName}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 700px; margin: 0 auto; padding: 40px 20px; color: #1a1a1a; }
  h1 { font-size: 24px; margin-bottom: 4px; }
  h2 { font-size: 16px; margin-top: 32px; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; color: #374151; }
  .header { border-left: 4px solid ${brandColor}; padding-left: 16px; margin-bottom: 24px; }
  .meta { color: #6b7280; font-size: 13px; }
  .stats { display: flex; gap: 24px; margin: 16px 0; }
  .stat { text-align: center; }
  .stat-value { font-size: 28px; font-weight: 700; }
  .stat-label { font-size: 11px; color: #6b7280; text-transform: uppercase; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
  th { color: #6b7280; font-size: 11px; text-transform: uppercase; }
  .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 11px; }
  @media print { body { padding: 0; } }
</style></head><body>
<div class="header">
  <p class="meta">Pipeline Report</p>
  <h1>${wsName}</h1>
  <p class="meta">Generated ${new Date().toLocaleDateString()}</p>
</div>
<div class="stats">
  <div class="stat"><div class="stat-value">${active.length}</div><div class="stat-label">Active</div></div>
  <div class="stat"><div class="stat-value">${completed}</div><div class="stat-label">Completed</div></div>
  <div class="stat"><div class="stat-value">${lost}</div><div class="stat-label">Lost</div></div>
  <div class="stat"><div class="stat-value">$${totalValue.toLocaleString()}</div><div class="stat-label">Pipeline Value</div></div>
</div>
<h2>Stages</h2>
<table><thead><tr><th>Stage</th><th>Clients</th><th>Overdue</th><th>Value</th></tr></thead><tbody>${pipelineRows}</tbody></table>
<div class="footer">Generated by Cadence · ${new Date().toLocaleDateString()}</div>
<script>window.print()</script>
</body></html>`;

  return new NextResponse(html, { headers: { "Content-Type": "text/html" } });
}
